### ISSUE TITLE
Could you teach me how to add custom SimpleIcons to my cloud skill component? 

### ISSUE THREAD

**Issue by Ryo-samuraiJP** [tsAppDevelopment/react-icon-cloud#12]
export const cloudProps: Omit<ICloud, "children"> = {
  containerProps: {
    style: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      width: "100%",
      paddingTop: 40,
    },
  },
  options: {
    reverse: true,
    depth: 1,
    wheelZoom: false,
    imageScale: 2,
    activeCursor: "default",
    tooltip: "native",
    initial: [0.1, -0.1],
    clickToFront: 500,
    tooltipDelay: 0,
    outlineColour: "#0000",
    maxSpeed: 0.04,
    minSpeed: 0.02,
    // dragControl: false,
  },
};

const icons = [
  "html5",
  "css3",
  "tailwindcss",
  "motion",
  "javascript",
  "ejs",
  "typescript",
  "react",
  "vite",
  "npm"
]

export const renderCustomIcon = (icon: SimpleIcon, theme: string) => {
  const bgHex = theme === "light" ? "#f3f2ef" : "#080510";
  const fallbackHex = theme === "light" ? "#6e6e73" : "#ffffff";
  const minContrastRatio = theme === "dark" ? 2 : 1.2;

  return renderSimpleIcon({
    icon,
    bgHex,
    fallbackHex,
    minContrastRatio,
    size: 42,
    aProps: {
      href: undefined,
      target: undefined,
      rel: undefined,
      onClick: (e: React.MouseEvent<HTMLAnchorElement, MouseEvent>) =>
        e.preventDefault(),
    },
  });
};

export type DynamicCloudProps = {
  iconSlugs: string[];
};

type IconData = Awaited<ReturnType<typeof fetchSimpleIcons>>;

export function IconCloud({ iconSlugs }: DynamicCloudProps) {
  const [data, setData] = useState<IconData | null>(null);
  const { theme } = useTheme();

  useEffect(() => {
    fetchSimpleIcons({ slugs: iconSlugs }).then(setData);
  }, [iconSlugs]);

  const renderedIcons = useMemo(() => {
    if (!data) return null;

    return Object.values(data.simpleIcons).map((icon) =>
      renderCustomIcon(icon, theme || "light")
    );
  }, [data, theme]);

  return (
    // @ts-expect-error: Cloud component does not accept children prop
    <Cloud {...cloudProps}>
      <>{renderedIcons}</>
    </Cloud>
  );
}

**Comment by teaguestockwell** [comment]
there are examples of how to add custom icons  in the [code sandbox](https://codesandbox.io/p/sandbox/react-icon-cloud-1xr9h). You may also render images inside of anchors under the cloud like this:

https://github.com/magicuidesign/magicui/blob/main/registry/default/magicui/icon-cloud.tsx
```
<a><img></img></a>
```

**Comment by Ryo-samuraiJP** [comment]
Thank you for your help. I appreciate it.
