### ISSUE TITLE
Icons In black Colour

### ISSUE THREAD

**Issue by sakthii05** [tsAppDevelopment/react-icon-cloud#14]
The icons are in default black colour, The data from SimpleIcon is not working as expected.  In prevoius the icons are respective to the default icon colour.

**Comment by teaguestockwell** [comment]
Thanks for creating an issue for this. I've fixed the icons rendering all black in 4.1.5. Please use version 4.1.6 since so that upstream changes in simple icon repo don't cause this issue again.
