### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by Brellio** [tsAppDevelopment/react-icon-cloud#5]
Hi there,

Is there a way to use custom icons in react-icon-cloud? 

Thanks

**Comment by teaguestockwell** [comment]
> Is there a way to use custom icons in react-icon-cloud?

Yes, you have a few options for tags that are not simple icons:
1. your svg only has one path
   - invoke `renderSimpleIcon` with an icon that has a hex, title and path and render the result  under a cloud
1. your svg has many paths / your using a png
   - create your own tags  `<a><img/></a>` elements and render them under the cloud. [Consider how the default renderer creates an img from an icon path](https://github.com/teaguestockwell/react-icon-cloud/blob/master/src/renderers/simple_icon.tsx ). You may use that as an example with a custom icon path or you may use an src on the img tags such as remote url that hosts a png or even base64.
   
I hope this helps, let me know what you come up with.

**Comment by Sacha338** [comment]
I don't understand ? Is this like that ?

```jsx
import React from "react";
import IconCloud from "./icon-cloud.config";

const slugs = [
  "typescript",
  "javascript",
  "dart",
  "java",
  "react",
  "flutter",
  "android",
  "html5",
  "css3",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
];

<a><img src="https://my.cool.img/path/to/image.png"/></a> // Is this like that ?

export function IconCloudDemo() {
  return (
    <div className="relative flex h-full w-full max-w-[32rem] items-center justify-center overflow-hidden rounded-lg border bg-background px-20 pb-20 pt-8 ">
      <IconCloud iconSlugs={slugs} />
    </div>
  );
}
```

**Comment by teaguestockwell** [comment]
The slugs are used to fetch svgs from a cdn, please use them as props for for a DynamicCloud like this: https://codesandbox.io/s/react-icon-cloud-1xr9h?file=/dynamic-cloud.tsx
